extend type Mutation {
  """
  ✨ Insert a single `Bid` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bid_insert(
    """
    Data object to insert into the table.
    """
    data: Bid_Data!
  ): Bid_KeyOutput! @fdc_generated(from: "Bid", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Click` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  click_insert(
    """
    Data object to insert into the table.
    """
    data: Click_Data!
  ): Click_KeyOutput! @fdc_generated(from: "Click", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Listing` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  listing_insert(
    """
    Data object to insert into the table.
    """
    data: Listing_Data!
  ): Listing_KeyOutput! @fdc_generated(from: "Listing", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Visit` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  visit_insert(
    """
    Data object to insert into the table.
    """
    data: Visit_Data!
  ): Visit_KeyOutput! @fdc_generated(from: "Visit", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Bid` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bid_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Bid_Data!]!
  ): [Bid_KeyOutput!]! @fdc_generated(from: "Bid", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Click` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  click_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Click_Data!]!
  ): [Click_KeyOutput!]! @fdc_generated(from: "Click", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Listing` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  listing_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Listing_Data!]!
  ): [Listing_KeyOutput!]! @fdc_generated(from: "Listing", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Visit` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  visit_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Visit_Data!]!
  ): [Visit_KeyOutput!]! @fdc_generated(from: "Visit", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Bid` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bid`.
  """
  bid_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Bid_Data!
  ): Bid_KeyOutput! @fdc_generated(from: "Bid", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Click` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Click`.
  """
  click_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Click_Data!
  ): Click_KeyOutput! @fdc_generated(from: "Click", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Listing` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Listing`.
  """
  listing_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Listing_Data!
  ): Listing_KeyOutput! @fdc_generated(from: "Listing", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Visit` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Visit`.
  """
  visit_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Visit_Data!
  ): Visit_KeyOutput! @fdc_generated(from: "Visit", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Bid` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bid`.
  """
  bid_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Bid_Data!]!
  ): [Bid_KeyOutput!]! @fdc_generated(from: "Bid", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Click` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Click`.
  """
  click_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Click_Data!]!
  ): [Click_KeyOutput!]! @fdc_generated(from: "Click", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Listing` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Listing`.
  """
  listing_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Listing_Data!]!
  ): [Listing_KeyOutput!]! @fdc_generated(from: "Listing", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Visit` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Visit`.
  """
  visit_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Visit_Data!]!
  ): [Visit_KeyOutput!]! @fdc_generated(from: "Visit", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Bid` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Bid` or `null` if not found.
  """
  bid_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Bid_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bid_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Bid_Data!
  ): Bid_KeyOutput @fdc_generated(from: "Bid", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Click` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Click` or `null` if not found.
  """
  click_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Click_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Click_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Click_Data!
  ): Click_KeyOutput @fdc_generated(from: "Click", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Listing` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Listing` or `null` if not found.
  """
  listing_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Listing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Listing_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Listing_Data!
  ): Listing_KeyOutput @fdc_generated(from: "Listing", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Visit` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Visit` or `null` if not found.
  """
  visit_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Visit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Visit_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Visit_Data!
  ): Visit_KeyOutput @fdc_generated(from: "Visit", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Bid` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  bid_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Bid_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Bid_Data!
  ): Int! @fdc_generated(from: "Bid", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Click` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  click_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Click_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Click_Data!
  ): Int! @fdc_generated(from: "Click", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Listing` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  listing_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Listing_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Listing_Data!
  ): Int! @fdc_generated(from: "Listing", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Visit` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  visit_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Visit_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Visit_Data!
  ): Int! @fdc_generated(from: "Visit", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Bid` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  bid_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Bid_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bid_FirstRow
  ): Bid_KeyOutput @fdc_generated(from: "Bid", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Click` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  click_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Click_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Click_FirstRow
  ): Click_KeyOutput @fdc_generated(from: "Click", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Listing` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  listing_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Listing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Listing_FirstRow
  ): Listing_KeyOutput @fdc_generated(from: "Listing", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Visit` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  visit_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Visit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Visit_FirstRow
  ): Visit_KeyOutput @fdc_generated(from: "Visit", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Bid` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  bid_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Bid_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Bid", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Click` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  click_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Click_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Click", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Listing` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  listing_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Listing_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Listing", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Visit` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  visit_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Visit_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Visit", purpose: DELETE_MULTIPLE)
}
