extend type AnnualLeaderboardEntry {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AnnualLeaderboardEntry", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table.
  """
  _count: Int! @fdc_generated(from: "AnnualLeaderboardEntry.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `lastBidAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastBidAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.lastBidAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `listingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  listingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.listingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `periodClicks` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodClicks_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.periodClicks", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `periodTotal` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodTotal_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.periodTotal", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `tagline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tagline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.tagline", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AnnualLeaderboardEntry` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AnnualLeaderboardEntry.url", purpose: QUERY_COUNT)
  """
  ✨ Sum the `periodClicks` field in the `AnnualLeaderboardEntry` table.
  """
  periodClicks_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "AnnualLeaderboardEntry.periodClicks", purpose: QUERY_SUM)
  """
  ✨ Sum the `periodTotal` field in the `AnnualLeaderboardEntry` table.
  """
  periodTotal_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "AnnualLeaderboardEntry.periodTotal", purpose: QUERY_SUM)
  """
  ✨ Average the `periodClicks` field in the `AnnualLeaderboardEntry` table.
  """
  periodClicks_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "AnnualLeaderboardEntry.periodClicks", purpose: QUERY_AVG)
  """
  ✨ Average the `periodTotal` field in the `AnnualLeaderboardEntry` table.
  """
  periodTotal_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "AnnualLeaderboardEntry.periodTotal", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `lastBidAt` field in the `AnnualLeaderboardEntry` table.
  """
  lastBidAt_min: Timestamp @fdc_generated(from: "AnnualLeaderboardEntry.lastBidAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodClicks` field in the `AnnualLeaderboardEntry` table.
  """
  periodClicks_min: Int @fdc_generated(from: "AnnualLeaderboardEntry.periodClicks", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodTotal` field in the `AnnualLeaderboardEntry` table.
  """
  periodTotal_min: Float @fdc_generated(from: "AnnualLeaderboardEntry.periodTotal", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `lastBidAt` field in the `AnnualLeaderboardEntry` table.
  """
  lastBidAt_max: Timestamp @fdc_generated(from: "AnnualLeaderboardEntry.lastBidAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodClicks` field in the `AnnualLeaderboardEntry` table.
  """
  periodClicks_max: Int @fdc_generated(from: "AnnualLeaderboardEntry.periodClicks", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodTotal` field in the `AnnualLeaderboardEntry` table.
  """
  periodTotal_max: Float @fdc_generated(from: "AnnualLeaderboardEntry.periodTotal", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "AnnualLeaderboardEntry", purpose: ENTITY_ID)
}
extend type Bid {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Bid", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Bid` table.
  """
  _count: Int! @fdc_generated(from: "Bid.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `amount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  amount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.amount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `bidderName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bidderName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.bidderName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `deltaAmount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  deltaAmount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.deltaAmount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `listingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  listingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.listingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `stripeSessionId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripeSessionId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.stripeSessionId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Bid` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Bid.url", purpose: QUERY_COUNT)
  """
  ✨ Sum the `amount` field in the `Bid` table.
  """
  amount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bid.amount", purpose: QUERY_SUM)
  """
  ✨ Sum the `deltaAmount` field in the `Bid` table.
  """
  deltaAmount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bid.deltaAmount", purpose: QUERY_SUM)
  """
  ✨ Average the `amount` field in the `Bid` table.
  """
  amount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bid.amount", purpose: QUERY_AVG)
  """
  ✨ Average the `deltaAmount` field in the `Bid` table.
  """
  deltaAmount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Bid.deltaAmount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `amount` field in the `Bid` table.
  """
  amount_min: Float @fdc_generated(from: "Bid.amount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Bid` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Bid.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `deltaAmount` field in the `Bid` table.
  """
  deltaAmount_min: Float @fdc_generated(from: "Bid.deltaAmount", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `amount` field in the `Bid` table.
  """
  amount_max: Float @fdc_generated(from: "Bid.amount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Bid` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Bid.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `deltaAmount` field in the `Bid` table.
  """
  deltaAmount_max: Float @fdc_generated(from: "Bid.deltaAmount", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Bid.id", purpose: ENTITY_ID)
}
extend type Click {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Click", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Click` table.
  """
  _count: Int! @fdc_generated(from: "Click.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Click` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Click.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Click` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Click.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Click` table where the `listingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  listingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Click.listingId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Click` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Click.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Click` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Click.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Click.id", purpose: ENTITY_ID)
}
extend type Listing {
  """
  ✨ List `Bid` objects in a one-to-many relationship (where `Bid`.`listing` is this object).
  """
  bids_on_listing(
    """
    Filter condition to narrow down the query results.
    """
    where: Bid_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Bid_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Bid_Having
  ): [Bid!]! @fdc_generated(from: "Bid.listing", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Click` objects in a one-to-many relationship (where `Click`.`listing` is this object).
  """
  clicks_on_listing(
    """
    Filter condition to narrow down the query results.
    """
    where: Click_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Click_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Click_Having
  ): [Click!]! @fdc_generated(from: "Click.listing", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Listing", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Listing` table.
  """
  _count: Int! @fdc_generated(from: "Listing.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `clickCount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clickCount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.clickCount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `currentBid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currentBid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.currentBid", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `ownerEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.ownerEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `tagline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tagline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.tagline", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Listing` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Listing.url", purpose: QUERY_COUNT)
  """
  ✨ Sum the `clickCount` field in the `Listing` table.
  """
  clickCount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Listing.clickCount", purpose: QUERY_SUM)
  """
  ✨ Sum the `currentBid` field in the `Listing` table.
  """
  currentBid_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Listing.currentBid", purpose: QUERY_SUM)
  """
  ✨ Average the `clickCount` field in the `Listing` table.
  """
  clickCount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Listing.clickCount", purpose: QUERY_AVG)
  """
  ✨ Average the `currentBid` field in the `Listing` table.
  """
  currentBid_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Listing.currentBid", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `clickCount` field in the `Listing` table.
  """
  clickCount_min: Int @fdc_generated(from: "Listing.clickCount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Listing` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Listing.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `currentBid` field in the `Listing` table.
  """
  currentBid_min: Float @fdc_generated(from: "Listing.currentBid", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Listing` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Listing.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `clickCount` field in the `Listing` table.
  """
  clickCount_max: Int @fdc_generated(from: "Listing.clickCount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Listing` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Listing.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `currentBid` field in the `Listing` table.
  """
  currentBid_max: Float @fdc_generated(from: "Listing.currentBid", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Listing` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Listing.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Listing.id", purpose: ENTITY_ID)
}
extend type MonthlyLeaderboardEntry {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "MonthlyLeaderboardEntry", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table.
  """
  _count: Int! @fdc_generated(from: "MonthlyLeaderboardEntry.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `lastBidAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastBidAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.lastBidAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `listingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  listingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.listingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `periodClicks` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodClicks_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.periodClicks", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `periodTotal` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodTotal_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.periodTotal", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `tagline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tagline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.tagline", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MonthlyLeaderboardEntry` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MonthlyLeaderboardEntry.url", purpose: QUERY_COUNT)
  """
  ✨ Sum the `periodClicks` field in the `MonthlyLeaderboardEntry` table.
  """
  periodClicks_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "MonthlyLeaderboardEntry.periodClicks", purpose: QUERY_SUM)
  """
  ✨ Sum the `periodTotal` field in the `MonthlyLeaderboardEntry` table.
  """
  periodTotal_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "MonthlyLeaderboardEntry.periodTotal", purpose: QUERY_SUM)
  """
  ✨ Average the `periodClicks` field in the `MonthlyLeaderboardEntry` table.
  """
  periodClicks_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "MonthlyLeaderboardEntry.periodClicks", purpose: QUERY_AVG)
  """
  ✨ Average the `periodTotal` field in the `MonthlyLeaderboardEntry` table.
  """
  periodTotal_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "MonthlyLeaderboardEntry.periodTotal", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `lastBidAt` field in the `MonthlyLeaderboardEntry` table.
  """
  lastBidAt_min: Timestamp @fdc_generated(from: "MonthlyLeaderboardEntry.lastBidAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodClicks` field in the `MonthlyLeaderboardEntry` table.
  """
  periodClicks_min: Int @fdc_generated(from: "MonthlyLeaderboardEntry.periodClicks", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodTotal` field in the `MonthlyLeaderboardEntry` table.
  """
  periodTotal_min: Float @fdc_generated(from: "MonthlyLeaderboardEntry.periodTotal", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `lastBidAt` field in the `MonthlyLeaderboardEntry` table.
  """
  lastBidAt_max: Timestamp @fdc_generated(from: "MonthlyLeaderboardEntry.lastBidAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodClicks` field in the `MonthlyLeaderboardEntry` table.
  """
  periodClicks_max: Int @fdc_generated(from: "MonthlyLeaderboardEntry.periodClicks", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodTotal` field in the `MonthlyLeaderboardEntry` table.
  """
  periodTotal_max: Float @fdc_generated(from: "MonthlyLeaderboardEntry.periodTotal", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "MonthlyLeaderboardEntry", purpose: ENTITY_ID)
}
extend type Visit {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Visit", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Visit` table.
  """
  _count: Int! @fdc_generated(from: "Visit.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Visit` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Visit.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Visit` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Visit.id", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Visit` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Visit.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Visit` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Visit.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Visit.id", purpose: ENTITY_ID)
}
extend type VisitStat {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "VisitStat", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `VisitStat` table.
  """
  _count: Int! @fdc_generated(from: "VisitStat.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VisitStat` table where the `last24h` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  last24h_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VisitStat.last24h", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VisitStat` table where the `lastHour` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastHour_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VisitStat.lastHour", purpose: QUERY_COUNT)
  """
  ✨ Sum the `last24h` field in the `VisitStat` table.
  """
  last24h_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VisitStat.last24h", purpose: QUERY_SUM)
  """
  ✨ Sum the `lastHour` field in the `VisitStat` table.
  """
  lastHour_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VisitStat.lastHour", purpose: QUERY_SUM)
  """
  ✨ Average the `last24h` field in the `VisitStat` table.
  """
  last24h_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VisitStat.last24h", purpose: QUERY_AVG)
  """
  ✨ Average the `lastHour` field in the `VisitStat` table.
  """
  lastHour_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VisitStat.lastHour", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `last24h` field in the `VisitStat` table.
  """
  last24h_min: Int @fdc_generated(from: "VisitStat.last24h", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastHour` field in the `VisitStat` table.
  """
  lastHour_min: Int @fdc_generated(from: "VisitStat.lastHour", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `last24h` field in the `VisitStat` table.
  """
  last24h_max: Int @fdc_generated(from: "VisitStat.last24h", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastHour` field in the `VisitStat` table.
  """
  lastHour_max: Int @fdc_generated(from: "VisitStat.lastHour", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "VisitStat", purpose: ENTITY_ID)
}
extend type WeeklyLeaderboardEntry {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "WeeklyLeaderboardEntry", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table.
  """
  _count: Int! @fdc_generated(from: "WeeklyLeaderboardEntry.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `lastBidAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastBidAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.lastBidAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `listingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  listingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.listingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `periodClicks` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodClicks_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.periodClicks", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `periodTotal` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  periodTotal_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.periodTotal", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `tagline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tagline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.tagline", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WeeklyLeaderboardEntry` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WeeklyLeaderboardEntry.url", purpose: QUERY_COUNT)
  """
  ✨ Sum the `periodClicks` field in the `WeeklyLeaderboardEntry` table.
  """
  periodClicks_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "WeeklyLeaderboardEntry.periodClicks", purpose: QUERY_SUM)
  """
  ✨ Sum the `periodTotal` field in the `WeeklyLeaderboardEntry` table.
  """
  periodTotal_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "WeeklyLeaderboardEntry.periodTotal", purpose: QUERY_SUM)
  """
  ✨ Average the `periodClicks` field in the `WeeklyLeaderboardEntry` table.
  """
  periodClicks_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "WeeklyLeaderboardEntry.periodClicks", purpose: QUERY_AVG)
  """
  ✨ Average the `periodTotal` field in the `WeeklyLeaderboardEntry` table.
  """
  periodTotal_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "WeeklyLeaderboardEntry.periodTotal", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `lastBidAt` field in the `WeeklyLeaderboardEntry` table.
  """
  lastBidAt_min: Timestamp @fdc_generated(from: "WeeklyLeaderboardEntry.lastBidAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodClicks` field in the `WeeklyLeaderboardEntry` table.
  """
  periodClicks_min: Int @fdc_generated(from: "WeeklyLeaderboardEntry.periodClicks", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `periodTotal` field in the `WeeklyLeaderboardEntry` table.
  """
  periodTotal_min: Float @fdc_generated(from: "WeeklyLeaderboardEntry.periodTotal", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `lastBidAt` field in the `WeeklyLeaderboardEntry` table.
  """
  lastBidAt_max: Timestamp @fdc_generated(from: "WeeklyLeaderboardEntry.lastBidAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodClicks` field in the `WeeklyLeaderboardEntry` table.
  """
  periodClicks_max: Int @fdc_generated(from: "WeeklyLeaderboardEntry.periodClicks", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `periodTotal` field in the `WeeklyLeaderboardEntry` table.
  """
  periodTotal_max: Float @fdc_generated(from: "WeeklyLeaderboardEntry.periodTotal", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "WeeklyLeaderboardEntry", purpose: ENTITY_ID)
}
